# Type make into the command line to automatically compile all of the files
program: runShell.c 
	gcc -o spaceInvaders  ./cpu/emulatorShell.c runShell.c ./cpu/helperFunctions.c ./cpu/dissassembler.c ./machine/ioPorts.c
