name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make normal
      run: make
    - name: make test
      run: make -f maketest
    - name: run test
      run: ./spaceInvadersTest
   # - name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
